### PR TITLE
Fix `upload` command

### LINKED ISSUE #61: 404 error responses on some Shopware API requests
In our most recent plugin upload:
```
  config: {
    url: 'plugins/{PLUGIN_ID}/binaries',
...
  response: {
    status: 404,
    statusText: 'Not Found',
...
    data: { success: false, code: 'Exception-0' }
```

I checked the requests when uploading the plugin _manually_. Seems like _some_ of the routes now have a "producers" part in it.

Manual upload:
```
POST https://api.shopware.com/producers/{PRODUCER_ID}/plugins/{PLUGIN_ID}/binaries/validate
POST https://api.shopware.com/producers/{PRODUCER_ID}/plugins/{PLUGIN_ID}/binaries
POST https://api.shopware.com/producers/{PRODUCER_ID}/plugins/{PLUGIN_ID}/binaries/${BINARY_ID}/file
 GET https://api.shopware.com/plugins/{PLUGIN_ID}
POST https://api.shopware.com/plugins/{PLUGIN_ID}/reviews
```

### PR DESCRIPTION
**Pull request by svenmuennich**
Shopware changed their store API to require a different sequence of requests when uploading a new binary or replacing an existing binary.

Old sequence:
1. Upload the plugin .zip file to create a new `binary` entity.
1. Set version, changelog, compatible Shopware versions and options on the `binary` received in 1. 
1. Save the modified `binary`.

New sequence:
1. Validate the plugin .zip file (only when creating a new version).
1. Create a new `binary` with version, changelog and compatible Shopware versions (only when creating a new version).
1. Upload the plugin .zip file for the new or existing `binary`.
1. Update version, changelog, compatible Shopware versions and options of the new or existing `binary` again.

Since Shopware stopped supporting ionCube encryption (it is no longer offered when creating a release via their account UI) I also deprecate the respective command option with this PR.

---

Fixes #61

### CODE REVIEW

**Comment by hanneswernery** [comment]
"briliant"
brilliant

File: lib/shopwareStoreCommander.js [hunk 1]
```diff
@@ -126,21 +127,82 @@ module.exports = class ShopwareStoreCommander {
...
+
+        const accountData = await this.getAccountData();
+        const { data: updatedBinary } = await this.client.put(
+            `producers/${accountData.producerId}/plugins/${plugin.id}/binaries/${binary.id}`,
+            {
+                changelogs,
+                softwareVersions: compatibleShopwareVersions,
+                licenseCheckRequired,
+                // ionCube encryption is no longer supported
+                ionCubeEncrypted: false,
```
Comment (hanneswernery) [inline lib/shopwareStoreCommander.js:178]: Can't we just skip sending the parameter then?

**Review by hanneswernery — APPROVED** [review]
Looks okay to me. One suggestion. You can choose to ignore it if you want to go ahead with the merge.

File: lib/shopwareStoreCommander.js (hunk 1 above)
Comment (svenmuennich) [reply lib/shopwareStoreCommander.js:178]: The request sent by the Shopware account app contained this in its payload. Without it I got an HTTP 400.
